# Generated by Django 6.0.3 on 2026-08-13 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="check_in",
            field=models.DateField(default=datetime.date(2026, 8, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="check_out",
            field=models.DateField(default=datetime.date(2026, 8, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
