# Generated by Django 6.0.3 on 2026-08-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_reservation_check_in_reservation_check_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("upcoming", "Upcoming"), ("cancelled", "Cancelled")],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
